### ISSUE TITLE
Population of organizations is failing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/populator#128]
**Describe the bug**

**To Reproduce**
1. Get latest server 'develop' branch
2. Get latest populator 'develop' branch
3. Use the default env settings to populate data
4. Run command `npm run populate` - error is thrown on organization population step
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ade5e395-5654-46d1-9483-efa660f0a9ae)

**Expected behavior**
Populator populates all data from the default file.

**Comment by techsmyth** [comment]
Please check with updates to populator (+client-lib) that were pushed as PRs today...
