### ISSUE TITLE
Stakeholders are added to an opportunity page twice.

### ISSUE THREAD

**Issue by Yvo-Hunink-The-Hague** [alkem-io/populator#41]
**Describe the bug**
Stakeholders are added to an opportunity page twice. (see screenshot)

**To Reproduce**
1. Add stakeholders to data sheet
2. compile 
3. Go to 'opportunity'
4. See stakeholders

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77057278/112484911-a8a76000-8d7a-11eb-85ee-6c84a8f6158c.png)

**Desktop (please complete the following information):**
 - Browser [brave]

**Comment by techsmyth** [comment]
Hey Yvo, can you send me through the latest version of your spreadsheet which showed this issue? Am not seeing it when I populate locally. Cheers, Neil

**Comment by techsmyth** [comment]
Clearning up backlog, issue is now stale + not reproducible locally.
